### ISSUE TITLE
Getting a build

### ISSUE THREAD

**Issue by ItsEternity** [tastybento/addon-acidisland#1]
Is it possible to get a build of this addon? I cannot seem to build it locally

**Comment by tastybento** [comment]
Sure. I’ll need to add it tomorrow though. What’s the issue? Maybe a dependency on another addon or Bskyblock I suspect.

**Comment by ItsEternity** [comment]
It is an error with building the commands (I have the latest bskyblock installed) 

`incompatible types: bskyblock.addon.acidisland.commands.AiCommand cannot be converted to us.tastybento.bskyblock.commands.IslandCommand`
